import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '@/utils/request'

const inter = Inter({ subsets: ['latin'] })


export async function getServerSideProps(context) {
 
   const genre = context.query.genre;

  const res = await fetch(`https://api.themoviedb.org/3/${requests[genre]?.url || requests.fetchTrending.url}`)
  const data = await res.json()
  return {
    props: {
      results: data.results
    }, // will be passed to the page component as props
  }
}

export default function Home({results}) {
   console.log(results)
  return (
    <>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         {/* Header */}

         <Header />
         {/* navbar */}
         <Nav />

     {/* REsults */}
         <Results data={results} />
    </>
  )
}
